name: Rasa Pro Studio Deployment
run-name: Studio ${{ inputs.uuid }}

on:
  push:
    branches:
      - ci-cd-integration-test
  workflow_dispatch:
    inputs:
      studioVersion:
        description: "Studio version to deploy. For example '0.1.4'"
        required: false
      uuid:
        description: "Smth"
        required: true

jobs:
  studio-webhook:
    name: Deployment
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: deploy rasa pro
        run: echo "deploying rasa pro"
