name: Rasa Pro Studio Deployment
run-name: Studio ${{ inputs.uuid }}

on:
  workflow_dispatch:
    inputs:
      uuid:
        description: "Smth"
        required: true
      modelUrl:
        description: "The URL of the model to deploy"
        required: true

jobs:
  studio-webhook:
    name: Deployment
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: deploy rasa pro
        run: echo "${{ inputs.modelUrl }}" && echo "${{ inputs.endpointsYml }}"
