name: Rasa Pro Studio Deployment

on:
  push:
    branches:
      - ci-cd-integration-tes
  workflow_dispatch:
    inputs:
      studioVersion:
        description: "Studio version to deploy. For example '0.1.4'"
        required: false

jobs:
  studio-webhook:
    name: Deployment
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: deploy rasa pro
        run: echo "deploying rasa pro"
